services:
  - type: web
    name: asr-parking-lot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migrate_db.py
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: asr-parking-db
          property: connectionString

databases:
  - name: asr-parking-db
    databaseName: asr_parking
    user: asr_parking_user